### ISSUE TITLE
Provide a way to not override *

### ISSUE THREAD

**Issue by tandrewnichols** [Chun-Yang/vim-action-ag#1]
Hey, I have a pull request that was about to submit to create a `g:vim_ag_maintain_star` flag to prevent overriding `*` (since I find `*` useful as is). However, I thought I'd open an issue first just to get your thoughts, because my own personal opinion would be to make overriding `*` opt _in_, rather than the default. However, if you do that, it almost feels like something you shouldn't even bother doing at all; it's just as short to let people map `*` to `<Plug>AgAnythingWord` themselves. I'm guessing, since you wrote this originally to override `*`, that you prefer that implementation. Thoughts?

**Comment by tandrewnichols** [comment]
Now that I'm reading it, that flag name seems weird. Doesn't need `vim` in it (or if it does, it should also have `anything` in it).

**Comment by Chun-Yang** [comment]
Hey @tandrewnichols , thank you for using this plugin!
1. I 100% agree that user should opt in for *.
2. About the naming: I just wanted to make it consistent with the plugin's name. Maybe the plugin's name is not good either. But consistent is mostly good. I would say we just keep the naming like that.
3. PLEASE send your PR. I like to learn from you!

**Comment by Chun-Yang** [comment]
Hey @tandrewnichols I am going to refactor and rename this repo. Please check the new one before you submit your PR. Thank you!

**Comment by tandrewnichols** [comment]
Thanks for the feedback. I'll watch the repo and keep an eye on it before sending a PR.
